(()=>{"use strict";
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const K={cards:"studyspace_flashcards",exams:"studyspace_exams",stats:"studyspace_stats",activity:"studyspace_activity_days",suggestions:"studyspace_suggestions"};
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const id=()=>Date.now()+"-"+Math.random().toString(16).slice(2);
let cards=read(K.cards,[]),exams=read(K.exams,[]),stats={attempts:0,correct:0,wrong:0,...read(K.stats,{})},activityDays=read(K.activity,[]),suggestions=read(K.suggestions,[]),quiz=[],quizIndex=0,revealed=false,toastTimer;

function toast(message){$("#toast").textContent=message;$("#toast").classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>$("#toast").classList.remove("show"),1900)}

function localDate(offset=0){const date=new Date;date.setDate(date.getDate()+offset);return new Date(date-date.getTimezoneOffset()*60000).toISOString().slice(0,10)}
function recordStudyActivity(){const today=localDate();if(!activityDays.includes(today)){activityDays.push(today);activityDays=activityDays.slice(-370);save(K.activity,activityDays)}if($("#homeStreak"))$("#homeStreak").textContent=getStudyStreak()}
function getStudyStreak(){const days=new Set(activityDays);let offset=days.has(localDate())?0:-1,count=0;while(days.has(localDate(offset))){count++;offset--}return count}

function route(){let page=location.hash.slice(1)||"home";if(!document.getElementById(page))page="home";$$(".page").forEach(x=>x.classList.toggle("active",x.id===page));$$("nav a").forEach(x=>x.classList.toggle("active",x.hash==="#"+page));$("nav").classList.remove("open");$("#menu").setAttribute("aria-expanded","false");scrollTo({top:0,behavior:"smooth"});if(page==="home")renderHomeSummary();if(page==="quiz")startQuiz();if(page==="progress")renderProgress();if(page==="countdown")renderExams()}

function renderHomeSummary(){const answered=stats.correct+stats.wrong,accuracy=answered?Math.round(stats.correct/answered*100):0;const upcoming=[...exams].filter(exam=>daysUntil(exam.date)>=0).sort((a,b)=>a.date.localeCompare(b.date));const next=upcoming[0];$("#homeStreak").textContent=getStudyStreak();$("#homeCards").textContent=cards.length;$("#homeAccuracy").textContent=accuracy+"%";$("#homeExamDays").textContent=next?daysUntil(next.date):"--";$("#homeExamSubject").textContent=next?next.subject:"No exam scheduled";$("#homeExamDate").textContent=next?new Date(next.date+"T00:00:00").toLocaleDateString(undefined,{weekday:"long",day:"numeric",month:"long"}):"Add a date to start your countdown.";$("#suggestionCount").textContent=suggestions.length}

function renderCards(){$("#cardCount").textContent=cards.length;$("#cardEmpty").hidden=cards.length>0;$("#cardList").innerHTML=cards.map((card,index)=>'<article class="card" tabindex="0" role="button" aria-label="Flashcard '+(index+1)+'. Press to flip."><div class="inner"><div class="face"><small>QUESTION '+(index+1)+'</small><p>'+escapeHTML(card.question)+'</p><div><span>Tap to reveal</span><button class="delete" data-card="'+card.id+'" aria-label="Delete card">x</button></div></div><div class="face back"><small>ANSWER</small><p>'+escapeHTML(card.answer)+'</p><div><span>Tap to flip back</span><button class="delete" data-card="'+card.id+'" aria-label="Delete card">x</button></div></div></div></article>').join("")}

$("#cardForm").addEventListener("submit",event=>{event.preventDefault();const question=$("#question").value.trim(),answer=$("#answer").value.trim();if(!question||!answer)return;cards.unshift({id:id(),question,answer});save(K.cards,cards);recordStudyActivity();event.target.reset();renderCards();toast("Flashcard added");$("#question").focus()});
$("#cardList").addEventListener("click",event=>{const button=event.target.closest("[data-card]");if(button){event.stopPropagation();cards=cards.filter(card=>card.id!==button.dataset.card);save(K.cards,cards);renderCards();toast("Flashcard deleted");return}const card=event.target.closest(".card");if(card)card.classList.toggle("flipped")});
$("#cardList").addEventListener("keydown",event=>{if((event.key==="Enter"||event.key===" ")&&event.target.classList.contains("card")){event.preventDefault();event.target.classList.toggle("flipped")}});

function startQuiz(){quiz=[...cards];quizIndex=0;revealed=false;renderQuiz()}
function renderQuiz(){const total=quiz.length,body=$("#qbody");$("#qcount").textContent=total?"Question "+Math.min(quizIndex+1,total)+" of "+total:"Question 0 of 0";$("#qbar").style.width=total?(quizIndex/total*100)+"%":"0%";
if(!total){body.innerHTML='<h2>No flashcards yet</h2><p>Create a few cards first, then come back for a quiz.</p><a class="btn" href="#flashcards">Create flashcards</a>';return}
if(quizIndex>=total){$("#qcount").textContent="Round complete";$("#qbar").style.width="100%";body.innerHTML='<h2>Round complete!</h2><p>You reviewed '+total+' card'+(total===1?"":"s")+'.</p><div class="actions"><button class="btn" id="again">Study again</button><a class="btn wrong" href="#progress">View progress</a></div>';$("#again").onclick=startQuiz;return}
const card=quiz[quizIndex];body.innerHTML=revealed?'<small>ANSWER</small><h2>'+escapeHTML(card.question)+'</h2><p class="answer">'+escapeHTML(card.answer)+'</p><div class="actions"><button class="btn correct" data-result="correct">Correct</button><button class="btn wrong" data-result="wrong">Wrong</button></div>':'<small>QUESTION</small><h2>'+escapeHTML(card.question)+'</h2><button class="btn" id="reveal">Reveal answer</button>';
if($("#reveal"))$("#reveal").onclick=()=>{revealed=true;renderQuiz()};$$("[data-result]",body).forEach(button=>button.onclick=()=>{stats.attempts++;stats[button.dataset.result]++;save(K.stats,stats);recordStudyActivity();quizIndex++;revealed=false;renderQuiz()})}

function renderProgress(){const answered=stats.correct+stats.wrong,accuracy=answered?Math.round(stats.correct/answered*100):0;$("#sCards").textContent=cards.length;$("#sAttempts").textContent=stats.attempts;$("#sCorrect").textContent=stats.correct;$("#sWrong").textContent=stats.wrong;$("#accuracy").textContent=$("#ringText").textContent=accuracy+"%";$("#ring").style.setProperty("--n",accuracy);$("#accuracyText").textContent=!answered?"Take your first quiz to start tracking accuracy.":accuracy>=80?"Excellent recall - keep that rhythm going.":accuracy>=60?"Good foundation. A little review will go a long way.":"Every miss helps. Review and try again."}
$("#reset").onclick=()=>{stats={attempts:0,correct:0,wrong:0};save(K.stats,stats);renderProgress();toast("Quiz stats reset")};

const daysUntil=date=>{const today=new Date;today.setHours(0,0,0,0);return Math.ceil((new Date(date+"T00:00:00")-today)/86400000)};
function renderExams(){exams.sort((a,b)=>a.date.localeCompare(b.date));$("#examEmpty").hidden=exams.length>0;$("#examList").innerHTML=exams.map(exam=>{const days=daysUntil(exam.date),label=days<0?"past":days===0?"today":Math.abs(days)===1?"day":"days";const date=new Date(exam.date+"T00:00:00").toLocaleDateString(undefined,{weekday:"short",day:"numeric",month:"short",year:"numeric"});return '<article class="exam"><div class="days"><b>'+Math.abs(days)+'</b><small>'+label+'</small></div><div><h3>'+escapeHTML(exam.subject)+'</h3><p>'+date+'</p></div><button data-exam="'+exam.id+'" aria-label="Delete exam">x</button></article>'}).join("")}
$("#examForm").addEventListener("submit",event=>{event.preventDefault();const subject=$("#subject").value.trim(),date=$("#date").value;if(!subject||!date)return;exams.push({id:id(),subject,date});save(K.exams,exams);event.target.reset();renderExams();toast("Exam added")});
$("#examList").onclick=event=>{const button=event.target.closest("[data-exam]");if(!button)return;exams=exams.filter(exam=>exam.id!==button.dataset.exam);save(K.exams,exams);renderExams();toast("Exam removed")};

$("#suggestionForm").addEventListener("submit",event=>{event.preventDefault();const text=$("#suggestionText").value.trim(),category=$("#suggestionCategory").value;if(!text)return;suggestions.unshift({id:id(),text,category,createdAt:new Date().toISOString()});save(K.suggestions,suggestions);event.target.reset();$("#suggestionCount").textContent=suggestions.length;toast("Thanks - your suggestion was saved")});

const stopWords=new Set("a an and are as at be been but by can for from had has have he her hers him his how i if in into is it its may more most not of on or our ours she should so than that the their theirs them then there these they this those through to too under up was we were what when where which who why will with would you your yours".split(" "));
function summarizeNotes(text,length){const clean=text.replace(/\s+/g," ").trim();const sentences=clean.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[clean];const words=clean.toLowerCase().match(/[a-z][a-z'-]{2,}/g)||[];const frequency={};words.filter(word=>!stopWords.has(word)).forEach(word=>frequency[word]=(frequency[word]||0)+1);const ranked=sentences.map((sentence,index)=>{const terms=sentence.toLowerCase().match(/[a-z][a-z'-]{2,}/g)||[];const useful=terms.filter(word=>!stopWords.has(word));const score=useful.reduce((sum,word)=>sum+(frequency[word]||0),0)/Math.max(useful.length,1)+(index===0?.7:0);return{sentence:sentence.trim(),index,score}});const requested={short:2,medium:4,long:6}[length]||4;const take=Math.min(Math.max(1,requested),sentences.length);const selected=ranked.sort((a,b)=>b.score-a.score).slice(0,take).sort((a,b)=>a.index-b.index);const keyTerms=Object.entries(frequency).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([word])=>word);return{sentences:selected.map(item=>item.sentence),keyTerms,originalWords:words.length,summaryWords:selected.reduce((sum,item)=>sum+item.sentence.split(/\s+/).length,0)}}

$("#noteInput").addEventListener("input",event=>{$("#noteCount").textContent=(event.target.value.trim().match(/\S+/g)||[]).length+" words"});
$("#summaryForm").addEventListener("submit",event=>{event.preventDefault();const notes=$("#noteInput").value.trim();if(notes.split(/\s+/).length<20){toast("Add at least 20 words for a useful summary");return}const result=summarizeNotes(notes,$("#summaryLength").value);const reduction=Math.max(0,Math.round((1-result.summaryWords/result.originalWords)*100));$("#summaryOutput").innerHTML='<div class="output-head"><div><small>YOUR STUDY BRIEF</small><h2>Key takeaways</h2></div><span>'+reduction+'% shorter</span></div><ul class="summary-points">'+result.sentences.map(sentence=>'<li>'+escapeHTML(sentence)+'</li>').join("")+'</ul><div class="key-terms"><span>KEY TERMS</span><div>'+result.keyTerms.map(term=>'<b>'+escapeHTML(term)+'</b>').join("")+'</div></div><button type="button" class="copy-summary text-btn" id="copySummary">Copy summary</button>';$("#copySummary").onclick=async()=>{const summary=result.sentences.join("\n\n");try{await navigator.clipboard.writeText(summary);toast("Summary copied")}catch{toast("Select the summary to copy it")}};recordStudyActivity();toast("Study brief created")});

const now=new Date;$("#date").min=new Date(now-now.getTimezoneOffset()*60000).toISOString().slice(0,10);
$("#menu").onclick=event=>{const open=$("nav").classList.toggle("open");event.currentTarget.setAttribute("aria-expanded",String(open))};
addEventListener("hashchange",route);renderCards();renderExams();renderProgress();route();
})();
